/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hjmejkywpwbutbywyctg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbWVqa3l3cHdidXRieXd5Y3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDE0ODUsImV4cCI6MjA3Mzg3NzQ4NX0.eHiccI9-UGgp-bfBT_JT_E7uH6bF9bKIZd98ClSIYGg"